name: Test and Build Dashboards Search Relevance Plugin

on: [pull_request, push]

env:
  PLUGIN_NAME: dashboards-search-relevance
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  Get-CI-Image-Tag:
    uses: opensearch-project/opensearch-build/.github/workflows/get-ci-image-tag.yml@c2498b758c08fb7bc48476509a5fc1b8dd5f7493 # main
    with:
      product: opensearch-dashboards

  build-and-test:
    name: Run unit tests
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Set env
        run: |
          opensearch_version=$(node -p "require('./opensearch_dashboards.json').opensearchDashboardsVersion")
          plugin_version=$(node -p "require('./package.json').version")
          major_version=$(echo $opensearch_version | cut -d. -f1)
          minor_version=$(echo $opensearch_version | cut -d. -f2)
          branch_version=${major_version}.${minor_version}
          opensearch_dashboards_branch=$branch_version
          base_branch=${{ github.base_ref }}
          if [ "$base_branch" = "main" ]; then
            opensearch_dashboards_branch=main
          fi
          echo "OPENSEARCH_DASHBOARDS_BRANCH=$opensearch_dashboards_branch" >> $GITHUB_ENV
          echo "OPENSEARCH_PLUGIN_VERSION=$plugin_version" >> $GITHUB_ENV
        shell: bash
      - name: Enable longer filenames
        if: ${{ matrix.os == 'windows-latest' }}
        run: git config --system core.longpaths true
      - name: Checkout OpenSearch-Dashboards
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          repository: opensearch-project/OpenSearch-Dashboards
          ref: ${{ env.OPENSEARCH_DASHBOARDS_BRANCH }}
          path: OpenSearch-Dashboards
      - name: Setup Node
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3
        with:
          node-version-file: './OpenSearch-Dashboards/.nvmrc'
          registry-url: 'https://registry.npmjs.org'
      - name: Install Yarn
        shell: bash
        run: |
          YARN_VERSION=$(node -p "require('./OpenSearch-Dashboards/package.json').engines.yarn")
          echo "Installing yarn@$YARN_VERSION"
          npm i -g yarn@$YARN_VERSION
      - run: node -v
      - run: yarn -v
      - name: Checkout dashboards-search-relevance plugin
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          path: OpenSearch-Dashboards/plugins/dashboards-search-relevance
      - name: Bootstrap plugin/OpenSearch-Dashboards
        run: |
          cd OpenSearch-Dashboards/plugins/dashboards-search-relevance
          yarn osd bootstrap
      - name: Run unit tests
        run: |
          cd OpenSearch-Dashboards/plugins/dashboards-search-relevance
          yarn test --coverage
      - name: Upload coverage
        uses: codecov/codecov-action@29386c70ef20e286228c72b668a06fd0e8399192 # v1
        with:
          flags: dashboards-search-relevance
          directory: ./OpenSearch-Dashboards/plugins/dashboards-search-relevance
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Build Artifact
        run: |
          cd OpenSearch-Dashboards/plugins/dashboards-search-relevance
          yarn build
          mv ./build/*.zip ./build/${{ env.PLUGIN_NAME }}-${{ env.OPENSEARCH_PLUGIN_VERSION }}.zip
        shell: bash
      - name: Upload Artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: dashboards-search-relevance-${{ matrix.os }}
          path: ./OpenSearch-Dashboards/plugins/dashboards-search-relevance/build
